In [19]:
#Es 1
mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
elemento = mat[1][2] # restituisce in questo caso l'elemento nella seconda riga e  terza colonna
print(elemento)


7


In [20]:
#Es 2
import numpy as np

#lista precedente
mat = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

# converti la lista in un array 
arr = np.array(mat)

# Accedi a un particolare elemento (es. seconda riga e terza colonna)
elemento = arr[1, 2]

print(elemento)

7


In [23]:
#Es 3
linear_data = np.array([x for x in range(27)])
reshaped_data = linear_data.reshape((3, 3, 3))

print("linear_data:")
print(linear_data)
print("Dimensione prima del reshape:", linear_data.shape)


print("\nreshaped_data:")
print(reshaped_data)
print("Dimensione dopo il reshape:", reshaped_data.shape) #per chiedere la grandezza dell'array

linear_data:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
Dimensione prima del reshape: (27,)

reshaped_data:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Dimensione dopo il reshape: (3, 3, 3)


In [38]:
#Es 4
lunghezza_struttura = np.linspace(0, 28.75, num=15)


for i, punto in enumerate(lunghezza_struttura, start=1):
    formatted_point = f'{round(punto, 3):.3f}'
    print(f"{i}° rivetto: {formatted_point} cm")


1° rivetto: 0.000 cm
2° rivetto: 2.054 cm
3° rivetto: 4.107 cm
4° rivetto: 6.161 cm
5° rivetto: 8.214 cm
6° rivetto: 10.268 cm
7° rivetto: 12.321 cm
8° rivetto: 14.375 cm
9° rivetto: 16.429 cm
10° rivetto: 18.482 cm
11° rivetto: 20.536 cm
12° rivetto: 22.589 cm
13° rivetto: 24.643 cm
14° rivetto: 26.696 cm
15° rivetto: 28.750 cm


In [24]:
# Es 5 mod 1
arr = np.array([[1, 1, 1, 1],
                [5, 1, 1, 1,],
                [20, -4, 0, 42]]) 
print(matrice)


[[ 1  1  1  1]
 [ 5  1  1  1]
 [20 -4  0 42]]


In [25]:
#Es 5 mod 2
mat = [[1, 1, 1, 1],[5, 1, 1, 1,],[20, -4, 0, 42]]

# converti la lista in un array 
arr = np.array(mat)
print (arr)


[[ 1  1  1  1]
 [ 5  1  1  1]
 [20 -4  0 42]]


In [9]:
#Es 6
import numpy as np

# Creazione dell'array 5x5
arr = np.array([[10, 22, 21, 8, 9],
                [9, 42, 3, 18, 11],
                [5, 4, 30, 12, 29],
                [37, 31, 7, 2, 26],
                [8, 6, 4, 33, 15]])

# Sottrazione del minimo e divisione per la differenza tra massimo e minimo
result_arr = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))

# Stampa l'array risultante
print(result_arr)


[[0.2   0.5   0.475 0.15  0.175]
 [0.175 1.    0.025 0.4   0.225]
 [0.075 0.05  0.7   0.25  0.675]
 [0.875 0.725 0.125 0.    0.6  ]
 [0.15  0.1   0.05  0.775 0.325]]
